package de.iteratec.loomo.state;

public enum Event {
    IDLE,
    VOICE_COMMAND_FOLLOW_ME,
    VOICE_COMMAND_WAIT,
    VOICE_COMMAND_STOP,
    VOICE_COMMAND_START,
    VOICE_COMMAND_RESET,
    VOICE_COMMAND_CONTINUE,
    DESTINATION_ARRIVED,
    FINISHED_NAV_INIT,
    FINISHED_INIT,
    VOICE_COMMAND_ELEVATOR,
    FINISHED_WIFI_CONNECTION,
    MANUAL_ELEVATOR_ESC;

}
